# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  govuk-notify-universal-comms:
    build:
      target: development
    image: govuk-notify-universal-comms-development
    container_name: govuk-notify-universal-comms-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    environment:
      NODE_OPTIONS: "$NODE_OPTIONS --experimental-vm-modules"
