services:
  govuk-notify-universal-comms:
    build:
      context: .
      target: production
    image: govuk-notify-universal-comms
    container_name: govuk-notify-universal-comms
    environment:
      APPINSIGHTS_CLOUDROLE: govuk-notify-universal-comms-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      NOTIFY_API_KEY: ${NOTIFY_API_KEY}
      NOTIFY_UNIVERSAL_EMAIL_TEMPLATE_ID: ${NOTIFY_UNIVERSAL_EMAIL_TEMPLATE_ID}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USERNAME: ${MESSAGE_QUEUE_USERNAME}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      COMMS_SUBSCRIPTION_ADDRESS: ${COMMS_SUBSCRIPTION_ADDRESS}
      COMMS_TOPIC_ADDRESS: ${COMMS_TOPIC_ADDRESS}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
